//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.21 at 04:16:13 PM MESZ 
//

package de.dzimmermann.rcp.bsgtaucha.mgt.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for actionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="actionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://de.dezimmermann.rcp.bsgtaucha.mgt/bsgtaucha-model}bandTypes"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="person-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="work-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actionType", propOrder = { "type", "description" })
public class ActionType {

	@XmlElement(required = true)
	protected BandTypes type;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String description;
	@XmlAttribute(name = "person-id")
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String personId;
	@XmlAttribute(name = "work-id")
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String workId;
	@XmlAttribute
	protected Integer amount;

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link BandTypes }
	 * 
	 */
	public BandTypes getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link BandTypes }
	 * 
	 */
	public void setType(BandTypes value) {
		this.type = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the personId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPersonId() {
		return personId;
	}

	/**
	 * Sets the value of the personId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPersonId(String value) {
		this.personId = value;
	}

	/**
	 * Gets the value of the workId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWorkId() {
		return workId;
	}

	/**
	 * Sets the value of the workId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWorkId(String value) {
		this.workId = value;
	}

	/**
	 * Gets the value of the amount property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * Sets the value of the amount property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setAmount(Integer value) {
		this.amount = value;
	}

	public ActionType getClone() {
		ActionType at = new ActionType();
		at.amount = amount != null ? new Integer(amount) : null;
		at.description = description != null ? new String(description) : null;
		at.personId = personId != null ? new String(personId) : null;
		at.type = type != null ? type : null;
		at.workId = workId != null ? new String(workId) : null;
		return at;
	}
}
