//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.21 at 04:16:13 PM MESZ 
//

package de.dzimmermann.rcp.bsgtaucha.mgt.model;

import java.util.Set;
import java.util.TreeSet;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for bandActionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="bandActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="band-type" type="{http://de.dezimmermann.rcp.bsgtaucha.mgt/bsgtaucha-model}bandTypes" />
 *       &lt;attribute name="amount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bandActionType", propOrder = { "track" })
public class BandActionType {

	@XmlAttribute(name = "band-type")
	protected BandTypes bandType;
	@XmlAttribute
	protected Integer amount;
	@XmlElement(required = false)
	protected Set<Integer> track;

	/**
	 * Gets the value of the bandType property.
	 * 
	 * @return possible object is {@link BandTypes }
	 * 
	 */
	public BandTypes getBandType() {
		return bandType;
	}

	/**
	 * Sets the value of the bandType property.
	 * 
	 * @param value
	 *            allowed object is {@link BandTypes }
	 * 
	 */
	public void setBandType(BandTypes value) {
		this.bandType = value;
	}

	/**
	 * Gets the value of the amount property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * Sets the value of the amount property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setAmount(Integer value) {
		this.amount = value;
	}

	public Set<Integer> getTrack() {
		if (track == null)
			track = new TreeSet<Integer>();
		return track;
	}

	public BandActionType getClone() {
		BandActionType bt = new BandActionType();
		bt.bandType = bandType != null ? BandTypes.valueOf(bandType.name())
				: null;
		bt.amount = amount != null ? new Integer(amount) : null;
		for (Integer i : getTrack()) {
			bt.getTrack().add(new Integer(i));
		}
		return bt;
	}
}
