//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.21 at 04:16:13 PM MESZ 
//

package de.dzimmermann.rcp.bsgtaucha.mgt.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the de.dzimmermann.rcp.bsgtaucha.mgt.model
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Root_QNAME = new QName(
			"http://de.dezimmermann.rcp.bsgtaucha.mgt/bsgtaucha-model", "root");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * de.dzimmermann.rcp.bsgtaucha.mgt.model
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link BandActionType }
	 * 
	 */
	public BandActionType createBandActionType() {
		return new BandActionType();
	}

	/**
	 * Create an instance of {@link BandType }
	 * 
	 */
	public BandType createBandType() {
		return new BandType();
	}

	/**
	 * Create an instance of {@link WorksType }
	 * 
	 */
	public WorksType createWorksType() {
		return new WorksType();
	}

	/**
	 * Create an instance of {@link WorkType }
	 * 
	 */
	public WorkType createWorkType() {
		return new WorkType();
	}

	/**
	 * Create an instance of {@link PersonType }
	 * 
	 */
	public PersonType createPersonType() {
		return new PersonType();
	}

	/**
	 * Create an instance of {@link ActionType }
	 * 
	 */
	public ActionType createActionType() {
		return new ActionType();
	}

	/**
	 * Create an instance of {@link PersonsType }
	 * 
	 */
	public PersonsType createPersonsType() {
		return new PersonsType();
	}

	/**
	 * Create an instance of {@link EntryType }
	 * 
	 */
	public EntryType createEntryType() {
		return new EntryType();
	}

	/**
	 * Create an instance of {@link RootType }
	 * 
	 */
	public RootType createRootType() {
		return new RootType();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link RootType }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://de.dezimmermann.rcp.bsgtaucha.mgt/bsgtaucha-model", name = "root")
	public JAXBElement<RootType> createRoot(RootType value) {
		return new JAXBElement<RootType>(_Root_QNAME, RootType.class, null,
				value);
	}

}
