//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.21 at 04:16:13 PM MESZ 
//

package de.dzimmermann.rcp.bsgtaucha.mgt.model;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for personType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="personType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postalcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="birthday" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="active-member" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personType", propOrder = { "name", "firstname", "street",
		"postalcode", "city", "phone", "mobile", "fax", "email" })
public class PersonType {

	@XmlElement(required = true)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String name;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String firstname;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String street;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String postalcode;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String city;
	@XmlElement(required = false)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String phone;
	@XmlElement(required = false)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String mobile;
	@XmlElement(required = false)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String fax;
	@XmlElement(required = false)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String email;

	@XmlAttribute(required = true)
	@XmlJavaTypeAdapter(EncryptionDecryptionAdapter.class)
	protected String id;
	@XmlAttribute(required = true)
	@XmlSchemaType(name = "date")
	@XmlJavaTypeAdapter(EncryptionDateAdapter.class)
	protected Date birthday;
	@XmlAttribute(name = "active-member")
	protected Boolean activeMember;

	@XmlAttribute(required = false)
	protected boolean removed;

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the firstname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFirstname() {
		return firstname;
	}

	/**
	 * Sets the value of the firstname property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFirstname(String value) {
		this.firstname = value;
	}

	/**
	 * Gets the value of the street property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStreet() {
		return street;
	}

	/**
	 * Sets the value of the street property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStreet(String value) {
		this.street = value;
	}

	/**
	 * Gets the value of the postalcode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPostalcode() {
		return postalcode;
	}

	/**
	 * Sets the value of the postalcode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPostalcode(String value) {
		this.postalcode = value;
	}

	/**
	 * Gets the value of the city property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Sets the value of the city property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCity(String value) {
		this.city = value;
	}

	/**
	 * Gets the value of the phone property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * Sets the value of the phone property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPhone(String value) {
		this.phone = value;
	}

	/**
	 * Gets the value of the mobile property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * Sets the value of the mobile property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMobile(String value) {
		this.mobile = value;
	}

	/**
	 * Gets the value of the fax property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * Sets the value of the fax property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFax(String value) {
		this.fax = value;
	}

	/**
	 * Gets the value of the email property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * Sets the value of the email property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEmail(String value) {
		this.email = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the birthday property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * Sets the value of the birthday property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setBirthday(Date value) {
		this.birthday = value;
	}

	/**
	 * Gets the value of the activeMember property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isActiveMember() {
		return activeMember;
	}

	/**
	 * Sets the value of the activeMember property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setActiveMember(Boolean value) {
		this.activeMember = value;
	}

	public boolean isRemoved() {
		return removed;
	}

	public void setRemoved(boolean removed) {
		this.removed = removed;
	}

	public PersonType getClone() {
		PersonType pt = new PersonType();
		pt.activeMember = activeMember != null ? new Boolean(activeMember)
				: null;
		pt.birthday = birthday != null ? new Date(birthday.getTime()) : null;
		pt.city = city != null ? new String(city) : null;
		pt.email = email != null ? new String(email) : null;
		pt.fax = fax != null ? new String(fax) : null;
		pt.firstname = firstname != null ? new String(firstname) : null;
		pt.id = id != null ? new String(id) : null;
		pt.mobile = mobile != null ? new String(mobile) : null;
		pt.name = name != null ? new String(name) : null;
		pt.phone = phone != null ? new String(phone) : null;
		pt.postalcode = postalcode != null ? new String(postalcode) : null;
		pt.removed = removed;
		pt.street = street != null ? new String(street) : null;
		return pt;
	}

	@Override
	public String toString() {
		return String
				.format("id=[%s]: name='%s', firstname='%s', street='%s', postalcode='%s', city='%s', birthday='%s'",
						id, name, firstname, street, postalcode, city,
						birthday.toString());
	}
}
